export type EditorialCmsLocale = "ar" | "nl" | "fr" | "en";

const COPY = {
  ar: {
    imageTitle: "صورة المقال",
    imageDescription: "ارفع صورة المقال مرة واحدة، وسيجهّز RijVia تلقائيًا المقاسات اللازمة للعرض والمشاركة.",
    imageEmpty: "المقال لا يحتوي على صورة",
    imageFile: "رفع صورة المقال",
    imageUpload: "رفع صورة المقال",
    imageReplace: "تغيير صورة المقال",
    imageAttached: "صورة المقال الحالية",
    imageFileHint: "JPEG أو PNG بحد أقصى 5 MB. يُنشأ اسم ملف مناسب لمحركات البحث تلقائيًا.",
    altTitle: "النص البديل للصورة",
    altDescription: "اكتب وصفًا قصيرًا ودقيقًا للصورة بكل لغة لتحسين الوصول وSEO.",
    editorTitle: "محتوى المقال",
    editorWrite: "كتابة",
    editorPreview: "معاينة",
    editorFormat: "التنسيق",
    editorStructure: "بنية النص",
    editorInsert: "إدراج",
    versionTitle: "سجل النسخ",
    versionDescription: "كل حفظ ينشئ نسخة جديدة. يمكنك معاينة نسخة سابقة أو تحميلها إلى المحرر دون حذف التاريخ.",
    versionCurrent: "النسخة الحالية",
    versionPreview: "معاينة",
    versionRestore: "تحميل للتعديل",
    versionRestoreConfirm: "سيتم تحميل محتوى هذه النسخة إلى المحرر. لن تُحذف أي نسخة من السجل.",
    versionLoaded: "تم تحميل النسخة إلى المحرر. عدّلها ثم احفظ لإنشاء نسخة جديدة.",
    startUpdate: "بدء تحديث المقال",
    startUpdateDescription: "أعد فتح المقال المنشور كمسودة تحديث مع الاحتفاظ بالنسخة المنشورة وسجلها.",
    updateStarted: "تم فتح المقال للتحديث ويمكنك الآن تعديل المحتوى وحفظ نسخة جديدة.",
    saveDraft: "حفظ نسخة جديدة",
    immutableHistory: "النسخ السابقة محفوظة كسجل تدقيق ولا تُحذف أو تُعدّل مباشرة.",
  },
  nl: {
    imageTitle: "Artikelafbeelding",
    imageDescription: "Upload één artikelafbeelding. RijVia maakt automatisch de formaten voor pagina's, kaarten en delen.",
    imageEmpty: "Dit artikel heeft geen afbeelding",
    imageFile: "Artikelafbeelding uploaden",
    imageUpload: "Artikelafbeelding uploaden",
    imageReplace: "Artikelafbeelding wijzigen",
    imageAttached: "Huidige artikelafbeelding",
    imageFileHint: "JPEG of PNG, maximaal 5 MB. Een SEO-vriendelijke bestandsnaam wordt automatisch gemaakt.",
    altTitle: "Alternatieve tekst",
    altDescription: "Schrijf per taal een korte, nauwkeurige beschrijving voor toegankelijkheid en SEO.",
    editorTitle: "Artikelinhoud",
    editorWrite: "Schrijven",
    editorPreview: "Voorbeeld",
    editorFormat: "Opmaak",
    editorStructure: "Structuur",
    editorInsert: "Invoegen",
    versionTitle: "Versiegeschiedenis",
    versionDescription: "Elke opslag maakt een nieuwe versie. Bekijk of laad een oudere versie zonder de geschiedenis te verwijderen.",
    versionCurrent: "Huidige versie",
    versionPreview: "Voorbeeld",
    versionRestore: "Laden om te bewerken",
    versionRestoreConfirm: "Deze versie wordt in de editor geladen. Er wordt niets uit de geschiedenis verwijderd.",
    versionLoaded: "De versie is in de editor geladen. Bewerk en sla op om een nieuwe versie te maken.",
    startUpdate: "Artikel bijwerken",
    startUpdateDescription: "Open een gepubliceerd artikel opnieuw als updateconcept met behoud van de gepubliceerde versie.",
    updateStarted: "Het artikel is geopend voor een update. Je kunt nu bewerken en een nieuwe versie opslaan.",
    saveDraft: "Nieuwe versie opslaan",
    immutableHistory: "Oudere versies blijven bewaard als auditgeschiedenis en worden niet rechtstreeks gewijzigd of verwijderd.",
  },
  fr: {
    imageTitle: "Image de l’article",
    imageDescription: "Importez une image d’article. RijVia génère automatiquement les formats nécessaires à l’affichage et au partage.",
    imageEmpty: "Cet article ne contient aucune image",
    imageFile: "Importer l’image de l’article",
    imageUpload: "Importer l’image de l’article",
    imageReplace: "Changer l’image de l’article",
    imageAttached: "Image actuelle de l’article",
    imageFileHint: "JPEG ou PNG, 5 Mo maximum. Un nom de fichier adapté au SEO est généré automatiquement.",
    altTitle: "Texte alternatif",
    altDescription: "Rédigez une description courte et précise dans chaque langue pour l’accessibilité et le SEO.",
    editorTitle: "Contenu de l’article",
    editorWrite: "Rédiger",
    editorPreview: "Aperçu",
    editorFormat: "Mise en forme",
    editorStructure: "Structure",
    editorInsert: "Insérer",
    versionTitle: "Historique des versions",
    versionDescription: "Chaque sauvegarde crée une nouvelle version. Prévisualisez ou rechargez une ancienne version sans supprimer l’historique.",
    versionCurrent: "Version actuelle",
    versionPreview: "Aperçu",
    versionRestore: "Charger pour modifier",
    versionRestoreConfirm: "Cette version sera chargée dans l’éditeur. Aucune version de l’historique ne sera supprimée.",
    versionLoaded: "La version a été chargée dans l’éditeur. Modifiez-la puis enregistrez pour créer une nouvelle version.",
    startUpdate: "Mettre l’article à jour",
    startUpdateDescription: "Rouvrez un article publié comme brouillon de mise à jour tout en conservant sa version publiée.",
    updateStarted: "L’article est ouvert pour mise à jour. Vous pouvez maintenant le modifier et enregistrer une nouvelle version.",
    saveDraft: "Enregistrer une nouvelle version",
    immutableHistory: "Les anciennes versions sont conservées comme historique d’audit et ne sont ni modifiées ni supprimées directement.",
  },
  en: {
    imageTitle: "Article image",
    imageDescription: "Upload one article image and RijVia will automatically prepare the sizes used across pages, cards, and sharing.",
    imageEmpty: "This article does not contain an image",
    imageFile: "Upload article image",
    imageUpload: "Upload article image",
    imageReplace: "Change article image",
    imageAttached: "Current article image",
    imageFileHint: "JPEG or PNG, up to 5 MB. An SEO-friendly filename is generated automatically.",
    altTitle: "Image alternative text",
    altDescription: "Write a short, accurate description in each language for accessibility and SEO.",
    editorTitle: "Article content",
    editorWrite: "Write",
    editorPreview: "Preview",
    editorFormat: "Formatting",
    editorStructure: "Structure",
    editorInsert: "Insert",
    versionTitle: "Version history",
    versionDescription: "Every save creates a new version. Preview or load an older version without deleting history.",
    versionCurrent: "Current version",
    versionPreview: "Preview",
    versionRestore: "Load for editing",
    versionRestoreConfirm: "This version will be loaded into the editor. No version will be deleted from history.",
    versionLoaded: "The version is loaded into the editor. Edit it and save to create a new version.",
    startUpdate: "Start article update",
    startUpdateDescription: "Reopen a published article as an update draft while preserving the published version and history.",
    updateStarted: "The article is open for updating. You can now edit and save a new version.",
    saveDraft: "Save new version",
    immutableHistory: "Older versions are preserved as audit history and are not edited or deleted directly.",
  },
} as const;

export function editorialCmsCopy(language: string) {
  const locale = language.toLowerCase() as EditorialCmsLocale;
  return COPY[locale] ?? COPY.en;
}
